image: maven:3.6.3  # Maven with Java

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - ls -la  # Debugging step to verify pom.xml exists
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        name: SonarQube Analysis
        image: openjdk:17
        caches:
          - maven
        script:
          - ls -la  # Debugging step to confirm pom.xml presence
          - mvn clean verify sonar:sonar \
              -Dsonar.projectKey=Dealers-MIS-reports-app \
              -Dsonar.host.url=http://44.207.67.158:9000 \
              -Dsonar.login=$squ_507fe91340a59206d513067df9df5d685ba1aec7
