image: maven:3.8.6-eclipse-temurin-17

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean verify

    - step:
        name: SonarQube Analysis
        script:
          - mvn sonar:sonar \
              -Dsonar.projectKey=Dealers-MIS-reports-app \
              -Dsonar.host.url="http://44.207.67.158:9000" \
              -Dsonar.login=squ_507fe91340a59206d513067df9df5d685ba1aec7

